source 'https://rubygems.org'

gem 'rspec_profiling', path: "../../"
gem 'pg'
gem 'rails'
gem 'sprockets'
gem 'sqlite3'

group :test do
  gem 'rspec-rails'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
end
